services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sward
      POSTGRES_PASSWORD: sward
      POSTGRES_DB: cursos_recursos_db
    ports:
      - "5435:5432"
  app:
    build: .
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://sward:sward@db:5432/cursos_recursos_db
      ENVIRONMENT: development
    depends_on:
      - db
